name: Basic Code Quality Check

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Runs on pull requests targeting the default branch
  pull_request:
    branches: ["main"]

jobs:
  basic-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Check Python installation
      run: |
        python --version
        echo "Basic repository check completed successfully!"